### ISSUE TITLE
DELETE manifest MUST be allowed only when <reference> is a digest

### ISSUE THREAD

**Issue by rchincha** [anuvu/zot#67]
@pmengelbert pointed out rightly that:

```
DELETE Manifest

Delete the manifest identified by name and reference. Note that a manifest can only be deleted by digest.
```

**Comment by pmengelbert** [comment]
What appears to be happening is that when a manifest is deleted by tag, the manifest itself is deleted, and so is the specified tag, but the other tags remain attached to the repository and aren't attached to any manifests.

Additionally, once the manifest has been deleted by tag, a DELETE request to the manifest URL (digest) yields a 202 response (where it should be 404 since the manifest was deleted by the tag).  Delete requests to the tags that are no longer attached to anything result in 404s.

**Comment by rchincha** [comment]
> 
> 
> What appears to be happening is that when a manifest is deleted by tag, the manifest itself is deleted, and so is the specified tag, but the other tags remain attached to the repository and aren't attached to any manifests.
> 
> Additionally, once the manifest has been deleted by tag, a DELETE request to the manifest URL (digest) yields a 202 response (where it should be 404 since the manifest was deleted by the tag). Delete requests to the tags that are no longer attached to anything result in 404s.

Opened a new issue #69 to track this.
